### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by thejon07**
i changes some tiny styles 
first one 
first-changes

changes its margin top and margin left
here's the updated version
update1

and the 2nd one is when it comes to responsiveness i changes the margin top hamburger menu about 2.1 rem
2nd one
and updated version is here
update2

i believe tiny changes makes websites more attractive and easy to use

### CODE REVIEW

**Comment by Volker-E** [comment]
Wikimedia Design Style Guide is deprecated and is going to be replaced by [Codex](https://doc.wikimedia.org/codex/latest/), Design System for Wikimedia.

**Comment by thejon07** [comment]
is codex open source? can i contribute on codex?

**Comment by thejon07** [comment]
is codex open source? can i contribute on codex?

**Comment by Volker-E** [comment]
Indeed it is. You would need to contribute via Wikimedia's infrastructure and code review software. Please see 
  - [How to contribute to Codex](https://doc.wikimedia.org/codex/latest/contributing/overview.html)
  - [How to contribute to Wikimedia/MediaWiki](https://www.mediawiki.org/wiki/How_to_contribute)
  - [How to become a MediaWiki hacker](https://www.mediawiki.org/wiki/How_to_become_a_MediaWiki_hacker)

**Comment by thejon07** [comment]
Thank you for your information. by the way i have one question i forked wikimedia-portal repository on my github repo than  i clone my repo to my local machine when i run npm install it throws an error. i can't start the development server .

**Pull request closed without merging**
