### PR TITLE
Extend “Icons” section with further agreed-on rules

### PR DESCRIPTION
**Pull request by Volker-E**

### CODE REVIEW

**Comment by reetssydney** [comment]
Hey Volker, I tried to update but do not appear to have permissions. Here's the updates I made to this file, plus updated icon images attached.

[icons-section updates.zip](https://github.com/wikimedia/WikimediaUI-Style-Guide/files/1098763/icons-section.updates.zip)

**Comment by Volker-E** [comment]
@reetssydney You mean to update this PR, correct?

**Comment by reetssydney** [comment]
@Volker-E yes please!

**Comment by Volker-E** [comment]
@reetssydney Do you have the imagery as SVGs as well? Or should this wait till @nirzar provides the huge SVG imagery file™?

**Comment by reetssydney** [comment]
hey @Volker-E : reckon we can update with the PNGs for now, and @nirzar can do the SVG cleanup afterwards :)

**Comment by Volker-E** [comment]
@reetssydney Ok, thanks! Minor note for future PRs: We should always avoid inline styles, they are neither well-performing, nor scalable. Left it in, because otherwise patch would get too far reaching. But this needs general approach!

**Pull request merged**
